language: csharp
solution: ToastTest.sln
matrix:
  include:
    # Ubuntu 16.04
    - os: linux
      dist: xenial
      sudo: required
    # Ubuntu 14.04
    - os: linux
      dist: trusty
      sudo: required
    # Windows
    - os: windows
